

[theme]

# Primary accent for interactive elements
primaryColor = '#ff3a22'

# Background color for the main content area
backgroundColor = '#c7af6b'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#B9F1C0'

# Color used for almost all text
textColor = '#628078'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
